name: app
services:
  api:
    image: api-image:1.0.0
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        NODE_VERSION: "22.22.0"
        ALPINE_VERSION: "3.22"
    environment:
      NODE_VERSION: "22.22.0"
      NODE_ENV: production
    container_name: api-container
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    container_name: db-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
