services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        NODE_VERSION: "22.20.0"
        ALPINE_VERSION: "3.20"
    environment:
      NODE_VERSION: 22.20.0
    container_name: api-container
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    container_name: db-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
